version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/data  # Menyimpan data database agar permanen
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:80" # Akses frontend di localhost:8080, diteruskan ke port 80 di container
    depends_on:
      - backend
    networks:
      - app-network

# Setup Docker Volume untuk Database SQLite
volumes:
  sqlite_data:

# Setup Network agar container bisa saling ngobrol
networks:
  app-network:
    driver: bridge
